GET http://localhost:5005/blogs

###
POST http://localhost:5005/blogs
Content-Type: application/json
X-Api-Key: thisIsABadPasswordExampleUseEnv

{
    "title":"my title",
    "body":"my body"
}

###
DELETE http://localhost:5005/